baseurl                 = "https://www.rancher.jp/site/"
languageCode            = "ja-jp"
title                   = "Rancher JP"
hasCJKLanguage          = true
copyright               = "© 2018 Rancher JP"

timeZone = 'Asia/Tokyo'

# Multilingual
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
themesdir = "../.."

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[permalinks]
    blog                = "/blog/:year/:month/:day/:slug/"
    study               = "/study/:slug/"
    docs                = "/docs/:slug/"
    translated          = "/translated/:slug/"
    post                = "/content/:year/:month/:day/:slug/"
    releasenote         = "/releasenote/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"
    archive             = "archives"


[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
